services:
  node-leader:
    build: ./app
    container_name: node-leader
    environment:
      NODE_NAME: leader
      ROLE: leader
    ports:
      - "8080:8080"
    networks:
      - distributed-net

  node-follower-1:
    build: ./app
    container_name: node-follower-1
    environment:
      NODE_NAME: follower-1
      ROLE: follower
    ports:
      - "8081:8080"
    networks:
      - distributed-net

  node-follower-2:
    build: ./app
    container_name: node-follower-2
    environment:
      NODE_NAME: follower-2
      ROLE: follower
    ports:
      - "8082:8080"
    networks:
      - distributed-net

networks:
  distributed-net:
    external: true
    name: distributed-net
